# Generated by Django 2.0.13 on 2020-10-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUserReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('noofChairs', models.IntegerField()),
                ('comingfrom', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('reservDate', models.DateField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CustomerReserv',
            },
        ),
    ]
